const BRAND_LOGOS: Record<string, string> = {
  abarth: "/images/brands/abarth.webp",
  "aston-martin": "/images/brands/aston-martin.svg",
  audi: "/images/brands/audi.svg",
  bmw: "/images/brands/bmw.svg",
  byd: "/images/brands/byd.svg",
  changan: "/images/brands/changan.svg",
  chery: "/images/brands/chery.svg",
  chevrolet: "/images/brands/chevrolet.svg",
  citroen: "/images/brands/citroen.png",
  ferrari: "/images/brands/ferrari.svg",
  fiat: "/images/brands/fiat.svg",
  ford: "/images/brands/ford.svg",
  foton: "/images/brands/foton.svg",
  gac: "/images/brands/gac.png",
  geely: "/images/brands/geely.svg",
  gwm: "/images/brands/gwm.svg",
  honda: "/images/brands/honda.svg",
  hyundai: "/images/brands/hyundai.svg",
  iveco: "/images/brands/iveco.png",
  jac: "/images/brands/jac.png",
  jaecoo: "/images/brands/jaecoo.png",
  jeep: "/images/brands/jeep.svg",
  jetour: "/images/brands/jetour.webp",
  kia: "/images/brands/kia.svg",
  lamborghini: "/images/brands/lamborghini.png",
  "land-rover": "/images/brands/land-rover.png",
  leapmotor: "/images/brands/leapmotor.png",
  lexus: "/images/brands/lexus.png",
  maserati: "/images/brands/maserati.png",
  mclaren: "/images/brands/mclaren.png",
  "mercedes-amg": "/images/brands/mercedes-amg.svg",
  "mercedes-benz": "/images/brands/mercedes-benz.svg",
  mg: "/images/brands/mg.png",
  mini: "/images/brands/mini.svg",
  mitsubishi: "/images/brands/mitsubishi.svg",
  nissan: "/images/brands/nissan.svg",
  omoda: "/images/brands/omoda.png",
  peugeot: "/images/brands/peugeot.svg",
  porsche: "/images/brands/porsche.png",
  ram: "/images/brands/ram.png",
  renault: "/images/brands/renault.svg",
  "rolls-royce": "/images/brands/rolls-royce.png",
  suzuki: "/images/brands/suzuki.png",
  toyota: "/images/brands/toyota.png",
  volkswagen: "/images/brands/volkswagen.png",
  volvo: "/images/brands/volvo.png",
  zeekr: "/images/brands/zeekr.png"
};

const BRAND_ALIASES: Record<string, string> = {
  "aston-martin-lagonda": "aston-martin",
  "audi-ag": "audi",
  "bmw-group": "bmw",
  "byd-auto": "byd",
  "caoa-changan": "changan",
  "changan-automobile": "changan",
  "caoa-chery": "chery",
  "chery-automobile": "chery",
  "citroen-automoveis": "citroen",
  "ferrari-automobili": "ferrari",
  "fiat-automoveis": "fiat",
  "ford-motor-company": "ford",
  "foton-motor": "foton",
  "gac-group": "gac",
  "gac-motor": "gac",
  "guangzhou-automobile": "gac",
  "geely-auto": "geely",
  "great-wall": "gwm",
  "great-wall-motor": "gwm",
  "great-wall-motors": "gwm",
  "gwm-motors": "gwm",
  "honda-automoveis": "honda",
  "hyundai-motor-company": "hyundai",
  "iveco-group": "iveco",
  "jac-motors": "jac",
  "jac-group": "jac",
  "kia-motors": "kia",
  "landrover": "land-rover",
  "leap-motor": "leapmotor",
  "mclaren-automotive": "mclaren",
  "mercedes-amg-performance": "mercedes-amg",
  "mercedes-benz-do-brasil": "mercedes-benz",
  mercedes: "mercedes-benz",
  "mg-motor": "mg",
  "mg-motors": "mg",
  "mini-cooper": "mini",
  "mitsubishi-motors": "mitsubishi",
  "hozon-auto": "neta",
  "neta-auto": "neta",
  "nissan-motor": "nissan",
  "ram-trucks": "ram",
  "renault-do-brasil": "renault",
  "rolls-royce-motor-cars": "rolls-royce",
  "suzuki-motor": "suzuki",
  "suzuki-motor-corporation": "suzuki",
  "volvo-cars": "volvo",
  vw: "volkswagen",
  "vw-volkswagen": "volkswagen"
};

function toBrandSlug(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function getBrandLogo(brandNameOrSlug: string): string | undefined {
  const slug = toBrandSlug(brandNameOrSlug);
  return BRAND_LOGOS[BRAND_ALIASES[slug] ?? slug];
}
